### ISSUE TITLE
Slow RViz performance in Docker container

### ISSUE THREAD

**Issue by el-geuse** [el-geuse/clyderos2#12]
RViz runs super slowly (~16fps) while running inside the docker container, and 60fps without. There doesn't seem to be any obvious problem that is causing this:

- Checking inside the container, it has access to all 16Gb of RAM.
- It has access to the GPU.

The last thing to obviously check is its compatibility with the GPU drivers. The best way I can think of doing this is switching from the base ROS image that we're using to the cuda image. That should definitely have the configuration set right to be optimising with Nvidia GPUs. If not, most likely some problem with RViz that has to be checked out.

**Comment by jsble** [comment]
Also, there seems to be an issue with launching Gazebo and RViz together, spawning the robot within the world. Currently being investigated.

**Comment by jsble** [comment]
running simulation (rviz + gazebo) in container results in <2fps, outside on local system results in ~20fps

**Comment by el-geuse** [comment]
The root cause of the problem was driver issues, mostly NVIDIA drivers being incorrect, as well as the NVIDIA container toolkit not being downloaded. Working well now with Gazebo and RViz!
![image](https://github.com/el-geuse/clyderos2/assets/44441463/83419be2-7f0e-4683-8622-f03d5ce99364)
